version: 2
updates:
    -   package-ecosystem: "composer"
        directory: "."
        schedule:
            interval: "weekly"
        groups:
            jetbrains-phpstorm-stubs:
                patterns:
                    - "jetbrains/phpstorm-stubs"
                update-types:
                    - "major"
            nikic/php-parser:
                patterns:
                    - "nikic/php-parser"
                update-types:
                    - "major"
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "vendor-bin/php-cs-fixer/"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "vendor-bin/phpstan/"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "vendor-bin/rector/"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "composer-root-version-checker"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "/Users/tfidry/Project/Humbug/php-scoper/fixtures/set027-laravel"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "/Users/tfidry/Project/Humbug/php-scoper/fixtures/set041-symfony64"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "composer"
        directory: "/Users/tfidry/Project/Humbug/php-scoper/fixtures/set042-symfony7"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"

    -   package-ecosystem: "github-actions"
        directory: ".github"
        schedule:
            interval: "weekly"
        groups:
            dependencies:
                patterns:
                    - "*"
