name: Build

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ created ]

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    # see https://getcomposer.org/doc/articles/troubleshooting.md#dependencies-on-the-root-package
    COMPOSER_ROOT_VERSION: 'dev-master'

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        name: "Unit-Tests: ${{ matrix.php }} - ${{ matrix.tools }}"
        strategy:
            fail-fast: false
            matrix:
                php: [ "7.4", "8.0" ]
                tools: [ "composer:v1", "composer:v2" ]
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: ${{ matrix.tools }}"
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   name: Run tests
                run: make tu

    e2e-tests:
        runs-on: ubuntu-latest
        name: "e2e-Tests: ${{ matrix.e2e }} - ${{ matrix.php }} - ${{ matrix.tools }}"
        strategy:
            fail-fast: false
            matrix:
                e2e:
                    - 'e2e_004'
                    - 'e2e_005'
                    - 'e2e_011'
                    - 'e2e_013'
                    - 'e2e_014'
                    - 'e2e_015'
                    - 'e2e_016'
                    - 'e2e_017'
                    - 'e2e_018'
                    - 'e2e_019'
                    - 'e2e_020'
                    - 'e2e_0210'
                    - 'e2e_0211'
                    - 'e2e_022'
                    - 'e2e_023'
                    - 'e2e_024'
                    - 'e2e_025'
                    - 'e2e_026'
                    - 'e2e_027'
                    - 'e2e_028'
                    - 'e2e_029'
                    - 'e2e_030'
                    - 'e2e_031'
                    - 'e2e_032'
                php: [ '7.4', '8.0' ]
                tools: [ 'composer:v2' ]
                include:
                    -   php: '7.4'
                        e2e: 'check-composer-root-version'
                        tools: 'composer:v2'

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: "phar.readonly=0"
                    tools: ${{ matrix.tools }}
                    coverage: pcov

            -   uses: "ramsey/composer-install@v1"

            -   name: Install tree
                if: matrix.e2e == 'e2e_032'
                run: sudo apt-get install -y tree

            -   name: Run e2e ${{ matrix.e2e }}
                run: make ${{ matrix.e2e }}

    build-phar:
        runs-on: ubuntu-latest
        name: Build PHAR

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    ini-values: 'phar.readonly=0'
                    tools: 'composer:v2'
                    coverage: 'none'

            -   uses: "ramsey/composer-install@v1"

            -   name: Build PHAR
                run: make build

            -   uses: actions/upload-artifact@v1
                name: Upload the PHAR artifact
                with:
                    name: php-scoper.phar
                    path: bin/php-scoper.phar

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs:
            - unit-tests
            - e2e-tests
            - build-phar
        if: github.event_name == 'release'
        steps:
            -   uses: actions/download-artifact@v1
                with:
                    name: php-scoper.phar
                    path: .

            -   name: Upload php-scoper.phar
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: php-scoper.phar
                    asset_name: php-scoper.phar
                    asset_content_type: application/zip
